version: "3.9"
services:
  url-key-generator:
    image: url-key-generator
    ports:
      - "8083:8080"
    environment:
    - REDIS_HOSTS=redisdb
  redisdb:
    image: redis
    ports:
    - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redisdb:6379
    ports:
    - "8081:8081"

