version: "3.9"
services:
  url-key-generator:
    image: url-key-generator
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
    - REDIS_HOSTS="redis"
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
    - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

